Repository faveosuite/faveo-invoicing-community, pull requests merged in 2020-05, with the labels that each got.

#1080 Unused file removal
  app/Box.php
  app/Organization.php
  app/Plugins/Stripe/Controllers/ProcessController.php
  app/Plugins/Stripe/views/middle-page.blade.php
  app/Services/Registrar.php
  app/UserOrganization.php
  resources/views/alpha.blade.php
  resources/views/app.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/new_register.blade.php
  resources/views/auth/new_reset.blade.php
  resources/views/auth/password.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/reset.blade.php
  resources/views/beta.blade.php
  resources/views/home.blade.php
  resources/views/loyout/loginlayout.blade.php
  resources/views/loyout/master.blade.php
  resources/views/themes/default1/front/auth/login-register.blade.php
  resources/views/themes/default1/layouts/front/master.blade.php
  resources/views/themes/default1/layouts/login.blade.php
  resources/views/themes/default1/stripe.blade.php
  resources/views/themes/default1/subscription/index.blade.php
  resources/views/vendor/cashier/receipt.blade.php
  resources/views/vendor/chumper.datatable/javascript.blade.php
  resources/views/vendor/chumper.datatable/template.blade.php
  resources/views/vendor/datatables/print.blade.php
  resources/views/welcome.blade.php
  storage/installed
  storagedist/product/php.ini
Labels: Requires Code Review

#1084 Subscription widget added
  app/Http/Controllers/DashboardController.php
  resources/views/themes/default1/common/dashboard.blade.php
Labels: Code Approved, Functionality Approved

#1089 UI issues
  app/Http/Controllers/Common/MailChimpController.php
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/Google2FAController.php
  app/Http/Controllers/Order/OrderController.php
  app/Http/Controllers/Order/RenewController.php
  app/Http/Controllers/User/AdminOrderInvoiceController.php
  app/Http/helpers.php
  app/Plugins/Stripe/Controllers/SettingsController.php
  public/common/js/2fa.js
  resources/views/mini_views/copied_flash_text.blade.php
  resources/views/mini_views/navigational_view.blade.php
  resources/views/themes/default1/front/clients/invoice.blade.php
  resources/views/themes/default1/front/clients/profile.blade.php
  resources/views/themes/default1/front/clients/show-order.blade.php
  resources/views/themes/default1/front/postCheckout.blade.php
  resources/views/themes/default1/invoice/index.blade.php
  resources/views/themes/default1/layouts/front/master.blade.php
  resources/views/themes/default1/order/show.blade.php
  resources/views/themes/default1/renew/popup.blade.php
  resources/views/themes/default1/user/2faModals.blade.php
Labels: Code Approved

#1096 Old version client bugfix
  app/Http/Controllers/DashboardController.php
  tests/Unit/Admin/Dashboard/DashboardControllerTest.php
Labels: Code Approved, Requires functionality review

#1087 Subscription filter
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/Front/BaseClientController.php
  app/Http/Controllers/Order/ExtendedOrderController.php
  app/Http/Controllers/Order/OrderController.php
  app/Http/helpers.php
  resources/views/mini_views/copied_flash_text.blade.php
  resources/views/themes/default1/common/dashboard.blade.php
  resources/views/themes/default1/front/auth/login-register.blade.php
  resources/views/themes/default1/front/clients/invoice.blade.php
  resources/views/themes/default1/front/clients/order1.blade.php
  resources/views/themes/default1/front/clients/show-order.blade.php
  resources/views/themes/default1/order/index.blade.php
  resources/views/themes/default1/order/show.blade.php
  resources/views/themes/default1/user/2faModals.blade.php
  tests/Unit/Admin/Order/ExtendedOrderControllerTest.php
Labels: Code Approved, Requires functionality review

#1097 csrf issue fixed
  app/Http/Controllers/Order/RenewController.php
  app/Http/Controllers/Product/BaseProductController.php
  app/Http/Controllers/Product/ProductTypeController.php
  app/Http/Controllers/User/ClientController.php
  app/Http/Controllers/User/CommentController.php
  app/Http/Kernel.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Http/helpers.php
  app/Traits/ApiKeySettings.php
  config/app.php
  config/installer.php
  resources/views/mini_views/navigational_view.blade.php
  resources/views/themes/default1/category/index.blade.php
  resources/views/themes/default1/common/Activity-Log.blade.php
  resources/views/themes/default1/common/chat/index.blade.php
  resources/views/themes/default1/common/email-log.blade.php
  resources/views/themes/default1/common/template/inbox.blade.php
  resources/views/themes/default1/front/contact.blade.php
  resources/views/themes/default1/front/page/index.blade.php
  resources/views/themes/default1/front/postCheckout.blade.php
  resources/views/themes/default1/front/widgets/index.blade.php
  resources/views/themes/default1/invoice/index.blade.php
  resources/views/themes/default1/layouts/front/master.blade.php
  resources/views/themes/default1/layouts/master.blade.php
  resources/views/themes/default1/licence/index.blade.php
  resources/views/themes/default1/order/index.blade.php
  resources/views/themes/default1/order/show.blade.php
  resources/views/themes/default1/payment/currency/index.blade.php
  resources/views/themes/default1/payment/promotion/index.blade.php
  resources/views/themes/default1/payment/tax/index.blade.php
  resources/views/themes/default1/product/group/index.blade.php
  resources/views/themes/default1/product/plan/index.blade.php
  resources/views/themes/default1/product/product/index.blade.php
  resources/views/themes/default1/user/2faModals.blade.php
  resources/views/themes/default1/user/client/index.blade.php
  resources/views/themes/default1/user/client/show.blade.php
  resources/views/themes/default1/user/verify.blade.php
  resources/views/vendor/installer/environment-wizard.blade.php
  routes/web.php
  vendor/rachidlaasri/laravel-installer/src/Controllers/EnvironmentController.php
  vendor/rachidlaasri/laravel-installer/src/Helpers/DatabaseManager.php
  vendor/rachidlaasri/laravel-installer/src/Helpers/EnvironmentManager.php
  vendor/rachidlaasri/laravel-installer/src/Lang/en/installer_messages.php
Labels: Code Approved, Functionality Approved, High Priority

#1126 Security Fixes
  app/Http/Controllers/Common/SocialMediaController.php
  app/Http/Controllers/Common/SystemManagerController.php
  app/Http/Controllers/Front/PageController.php
  app/Http/Controllers/Github/GithubController.php
  app/Http/Controllers/Order/RenewController.php
  app/Http/Controllers/Payment/CurrencyController.php
  app/Http/Controllers/Product/BaseProductController.php
  app/Http/Controllers/Product/PlanController.php
  app/Http/Controllers/Product/ProductTypeController.php
  app/Http/Controllers/User/ClientController.php
  app/Http/Controllers/User/CommentController.php
  app/Http/Controllers/User/ProfileController.php
  app/Http/Kernel.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Http/helpers.php
  app/Plugins/Stripe/Controllers/SettingsController.php
  app/Traits/ApiKeySettings.php
  app/Traits/Upload/ChunkUpload.php
  config/app.php
  config/installer.php
  resources/views/mini_views/navigational_view.blade.php
  resources/views/themes/default1/category/index.blade.php
  resources/views/themes/default1/common/Activity-Log.blade.php
  resources/views/themes/default1/common/chat/index.blade.php
  resources/views/themes/default1/common/dashboard.blade.php
  resources/views/themes/default1/common/email-log.blade.php
  resources/views/themes/default1/common/template/inbox.blade.php
  resources/views/themes/default1/front/auth/reset.blade.php
  resources/views/themes/default1/front/clients/profile.blade.php
  resources/views/themes/default1/front/contact.blade.php
  resources/views/themes/default1/front/enableTwoFactor.blade.php
  resources/views/themes/default1/front/page/index.blade.php
  resources/views/themes/default1/front/postCheckout.blade.php
  resources/views/themes/default1/front/recoveryCode.blade.php
  resources/views/themes/default1/front/widgets/index.blade.php
  resources/views/themes/default1/invoice/index.blade.php
  resources/views/themes/default1/layouts/front/master.blade.php
  resources/views/themes/default1/layouts/master.blade.php
  resources/views/themes/default1/licence/index.blade.php
  resources/views/themes/default1/order/index.blade.php
  resources/views/themes/default1/order/show.blade.php
  resources/views/themes/default1/payment/currency/index.blade.php
  resources/views/themes/default1/payment/promotion/index.blade.php
  resources/views/themes/default1/payment/tax/index.blade.php
  resources/views/themes/default1/product/group/index.blade.php
  resources/views/themes/default1/product/plan/index.blade.php
  resources/views/themes/default1/product/product/index.blade.php
  resources/views/themes/default1/user/2faModals.blade.php
  resources/views/themes/default1/user/client/index.blade.php
  resources/views/themes/default1/user/client/show.blade.php
  resources/views/themes/default1/user/verify.blade.php
  resources/views/vendor/installer/environment-wizard.blade.php
  routes/web.php
  vendor/arcanedev/log-viewer/src/Http/Controllers/LogViewerController.php
  vendor/laravel/framework/src/Illuminate/Foundation/Auth/RegistersUsers.php
  vendor/rachidlaasri/laravel-installer/src/Controllers/EnvironmentController.php
  vendor/rachidlaasri/laravel-installer/src/Helpers/DatabaseManager.php
  vendor/rachidlaasri/laravel-installer/src/Helpers/EnvironmentManager.php
  vendor/rachidlaasri/laravel-installer/src/Lang/en/installer_messages.php
Labels: High Priority
