Repository faveosuite/faveo-invoicing-community, pull requests merged in 2023-12, with the labels that each got.

#2794 Apply fixes from StyleCI
  app/Console/Kernel.php
Labels: size/XS

#2803 Apply fixes from StyleCI
  app/Http/Controllers/Common/SocialMediaController.php
Labels: size/XS

#2796 Undefined variable $order_id
  app/Http/Controllers/Order/RenewController.php
Labels: Code Approved, QA: Functionality Approved, size/XS

#2742 License Manager Changes
  app/Http/Controllers/License/LicenseController.php
Labels: Enhancement, Code Approved, QA: Functionality Approved, size/XS

#2807 Apply fixes from StyleCI
  routes/web.php
Labels: size/XS

#2781 License Code and Knowledge base URL
  app/Http/Controllers/Order/BaseOrderController.php
  app/Model/Common/Setting.php
  database/migrations/2023_11_11_063258_add_knowledgebase_to_settings.php
  database/seeders/v3_0_5/DatabaseSeeder.php
  resources/views/themes/default1/common/setting/system.blade.php
Labels: Bug, Code Approved, QA: Functionality Approved, size/L, PD: Demo Approved

#2809 Apply fixes from StyleCI
  config/horizon.php
Labels: size/XS

#2795 Stripe duplicate transaction in auto subscription
  app/Console/Kernel.php
Labels: Code Approved, QA: Functionality Approved, size/S

#2815 Apply fixes from StyleCI
  app/Http/Controllers/Front/PageController.php
Labels: size/XS

#2817 Apply fixes from StyleCI
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/User/ClientController.php
Labels: size/L

#2819 Apply fixes from StyleCI
  app/Console/Commands/moveImages.php
  app/Console/Kernel.php
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Auth/BaseAuthController.php
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Common/BaseCronController.php
  app/Http/Controllers/Common/BaseMailChimpController.php
  app/Http/Controllers/Common/BaseSettingsController.php
  app/Http/Controllers/Common/CronController.php
  app/Http/Controllers/Common/SettingsController.php
  app/Http/Controllers/Common/Twitter/Util.php
  app/Http/Controllers/Front/CartController.php
  app/Http/Controllers/Front/CheckoutController.php
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/Front/PageController.php
  app/Http/Controllers/Front/WidgetController.php
  app/Http/Controllers/Github/GithubController.php
  app/Http/Controllers/Google2FAController.php
  app/Http/Controllers/Order/InvoiceController.php
  app/Http/Controllers/Order/OrderController.php
  app/Http/Controllers/Order/RenewController.php
  app/Http/Controllers/Order/TaxRatesAndCodeExpiryController.php
  app/Http/Controllers/Product/AddonController.php
  app/Http/Controllers/RazorpayController.php
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
  app/Http/Controllers/Tenancy/TenantController.php
  app/Http/Controllers/User/ClientController.php
  app/Http/Requests/Common/SettingsRequest.php
  app/Http/Requests/Front/PageRequest.php
  app/Http/Requests/User/ClientRequest.php
  app/Http/Requests/User/ProfileRequest.php
  app/Plugins/Stripe/Controllers/SettingsController.php
  config/datatables.php
  config/debugbar.php
  config/gravatar.php
  config/transform.php
  lang/en/message.php
  tests/Unit/Admin/User/ClientControllerTest.php
  tests/Unit/PageControllerTest.php
Labels: size/L

#2821 Apply fixes from StyleCI
  app/Http/Controllers/Common/PhpMailController.php
  app/Http/Controllers/Order/InvoiceController.php
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
  app/Http/Controllers/Tenancy/TenantController.php
  lang/en/message.php
Labels: size/M

#2828 Apply fixes from StyleCI
  app/Http/Controllers/Front/ClientController.php
Labels: size/XS

#2829 Apply fixes from StyleCI
  app/Http/Controllers/Common/CronController.php
Labels: size/XS

#2832 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
Labels: size/XS

#2831 Added js files
  resources/views/themes/default1/layouts/master.blade.php
Labels: Requires Code Review, size/XS

#2839 Apply fixes from StyleCI
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/User/AdminOrderInvoiceController.php
Labels: size/S

#2840 Apply fixes from StyleCI
  app/Http/Controllers/Order/ExtendedBaseInvoiceController.php
Labels: size/XS

#2825 Searching
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/User/AdminOrderInvoiceController.php
Labels: Code Approved, QA: Functionality Approved, size/L, PD: Demo Approved

#2847 Apply fixes from StyleCI
  app/Http/Controllers/Front/ClientController.php
Labels: size/XS
