Repository faveosuite/faveo-invoicing-community, pull requests merged in 2023-09, with the labels that each got.

#2559 Apply fixes from StyleCI
  app/Http/Controllers/Front/PageController.php
Labels: size/XS

#2560 Apply fixes from StyleCI
  app/Http/Controllers/Common/TemplateController.php
  app/Http/Controllers/Front/PageController.php
Labels: size/M

#2561 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
Labels: size/XS

#2562 Apply fixes from StyleCI
  app/Http/Controllers/Common/CronController.php
  app/Http/Controllers/Common/TemplateController.php
  app/Http/Controllers/Order/BaseOrderController.php
Labels: size/S

#2563 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
Labels: size/S

#2564 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
Labels: size/XS

#2569 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
Labels: size/XS

#2570 Apply fixes from StyleCI
  app/Http/Controllers/Tenancy/TenantController.php
Labels: size/XS

#2581 Apply fixes from StyleCI
  app/Http/Controllers/Front/PageController.php
  app/Model/Common/Setting.php
  database/migrations/2023_09_07_090604_add_phone_code_to_settings.php
Labels: size/S

#2583 Apply fixes from StyleCI
  app/Http/Controllers/Front/PageController.php
Labels: size/XS

#2594 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/LicenseBillOrders.php
  routes/api.php
Labels: size/M

#2598 Apply fixes from StyleCI
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Common/CronController.php
  app/Http/Controllers/Common/PhpMailController.php
  app/Http/Controllers/FreeTrailController.php
  app/Http/Controllers/Front/PageController.php
  app/Http/Controllers/Order/BaseOrderController.php
Labels: size/M

#2601 Apply fixes from StyleCI
  app/Http/Controllers/FreeTrailController.php
  app/Http/Controllers/Order/BaseOrderController.php
  app/Plugins/Stripe/Controllers/SettingsController.php
Labels: size/S

#2603 Apply fixes from StyleCI
  app/Http/Controllers/Auth/ForgotPasswordController.php
Labels: size/XS

#2605 Version expiry api corrections
  app/Http/Controllers/BaseHomeController.php
Labels: Bug, QA: Functionality Approved, size/M

#2610 Apply fixes from StyleCI
  app/Http/Controllers/Front/BaseClientController.php
  app/Http/Controllers/Front/CartController.php
  app/Http/Controllers/Front/CheckoutController.php
  app/Http/Controllers/Front/PageController.php
  app/Http/Controllers/Order/ExtendedOrderController.php
  app/Http/Controllers/Order/InvoiceController.php
  app/Http/Controllers/Product/ExtendedBaseProductController.php
  app/Http/Controllers/RazorpayController.php
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
  app/Model/Order/Invoice.php
  app/Plugins/Stripe/Controllers/SettingsController.php
  bootstrap/cache/packages.php
  bootstrap/cache/services.php
  routes/web.php
Labels: size/XXL

#2612 Apply fixes from StyleCI
  app/Http/Controllers/Front/CheckoutController.php
Labels: size/XS

#2613 Apply fixes from StyleCI
  app/Http/Controllers/LicenseBillOrders.php
  routes/web.php
Labels: size/S

#2615 Apply fixes from StyleCI
  app/Http/Controllers/Order/InvoiceController.php
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
Labels: size/XS

#2618 Apply fixes from StyleCI
  app/Http/Controllers/Common/PhpMailController.php
Labels: size/XS

#2621 Apply fixes from StyleCI
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
  lang/en/message.php
Labels: size/XS

#2623 Apply fixes from StyleCI
  app/Http/Controllers/Common/CronController.php
  app/Plugins/Stripe/Controllers/SettingsController.php
Labels: size/S

#2626 Apply fixes from StyleCI
  app/Http/Controllers/Auth/BaseAuthController.php
  app/VerificationAttempt.php
Labels: size/S

#2628 Apply fixes from StyleCI
  app/Http/Controllers/Front/CartController.php
Labels: size/XS

#2630 Apply fixes from StyleCI
  app/Http/Controllers/Front/CartController.php
Labels: size/XS

#2634 Apply fixes from StyleCI
  app/Http/Controllers/Front/CartController.php
Labels: size/XS

#2635 Apply fixes from StyleCI
  app/Http/Controllers/Front/CartController.php
Labels: size/XS

#2636 Apply fixes from StyleCI
  app/Http/Controllers/Front/CartController.php
Labels: size/XS

#2637 Apply fixes from StyleCI
  app/Http/Controllers/Front/CheckoutController.php
Labels: size/XS

#2638 Apply fixes from StyleCI
  app/Http/Controllers/Order/BaseRenewController.php
Labels: size/XS

#2640 Apply fixes from StyleCI
  app/Http/Controllers/Front/CartController.php
  app/Http/Controllers/Order/InvoiceController.php
Labels: size/XS

#2645 Apply fixes from StyleCI
  app/Http/Controllers/Common/CronController.php
  app/Http/Controllers/Front/ClientController.php
  app/Plugins/Stripe/Controllers/SettingsController.php
  database/migrations/2023_09_21_073606_add_order_id_to_auto_renewals_table.php
Labels: size/S

#2646 Apply fixes from StyleCI
  database/migrations/2023_09_21_073606_add_order_id_to_auto_renewals_table.php
Labels: size/S

#2648 Apply fixes from StyleCI
  app/Http/Controllers/RazorpayController.php
  app/Plugins/Stripe/Controllers/SettingsController.php
Labels: size/XS

#2649 Apply fixes from StyleCI
  app/Http/Controllers/User/AdminOrderInvoiceController.php
Labels: size/XS

#2650 Apply fixes from StyleCI
  app/Http/Controllers/Front/ClientController.php
Labels: size/XS

#2651 Apply fixes from StyleCI
  app/Http/Controllers/Front/CheckoutController.php
  app/Http/Controllers/Order/RenewController.php
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
  app/Plugins/Stripe/Controllers/SettingsController.php
Labels: size/S

#2652 Apply fixes from StyleCI
  app/Http/Controllers/Order/RenewController.php
Labels: size/XS

#2653 Apply fixes from StyleCI
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
Labels: size/S

#2656 Apply fixes from StyleCI
  app/Http/Controllers/Order/BaseOrderController.php
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
Labels: size/M

#2657 Apply fixes from StyleCI
  app/Http/Controllers/Order/BaseOrderController.php
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
Labels: size/M
