Repository faveosuite/faveo-invoicing-community, pull requests merged in 2024-02, with the labels that each got.

#2890 Apply fixes from StyleCI
  app/Http/Controllers/Front/PageController.php
  tests/Unit/PageControllerTest.php
Labels: size/S

#2891 Apply fixes from StyleCI
  app/Http/Controllers/HomeController.php
Labels: size/S

#2892 Some depreciation
  app/Http/Controllers/HomeController.php
Labels: size/M

#2898 Apply fixes from StyleCI
  tests/Unit/Admin/User/ClientControllerTest.php
Labels: size/M

#2899 Apply fixes from StyleCI
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/Order/OrderSearchController.php
Labels: size/M

#2902 Apply fixes from StyleCI
  app/Http/Controllers/Product/ExtendedBaseProductController.php
  app/Model/Product/ProductUpload.php
  app/ReleaseType.php
  database/migrations/2024_02_15_044608_add_release_id_to_product_uploads_table.php
Labels: size/S

#2903 Apply fixes from StyleCI
  app/Http/Controllers/Common/CronController.php
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/RazorpayController.php
  app/Plugins/Stripe/Controllers/SettingsController.php
  app/Plugins/Stripe/routes.php
Labels: size/XL

#2904 Apply fixes from StyleCI
  app/Http/Controllers/RazorpayController.php
Labels: size/M

#2905 Apply fixes from StyleCI
  app/Http/Controllers/Common/CronController.php
  app/Http/Controllers/Front/ClientController.php
  app/Plugins/Stripe/Controllers/SettingsController.php
Labels: size/L

#2911 Apply fixes from StyleCI
  app/Auto_renewal.php
Labels: size/XS

#2912 Apply fixes from StyleCI
  tests/Unit/CronControllerTest.php
Labels: size/XS

#2914 Apply fixes from StyleCI
  app/Http/Controllers/HomeController.php
Labels: size/XS

#2916 Apply fixes from StyleCI
  app/Plugins/Stripe/Controllers/SettingsController.php
Labels: size/XS

#2919 Apply fixes from StyleCI
  tests/Unit/Client/Stripe/SettingsControllerTest.php
Labels: size/M

#2920 Apply fixes from StyleCI
  app/Http/Controllers/Product/ExtendedBaseProductController.php
  app/Model/Product/ProductUpload.php
  database/migrations/2024_02_29_054007_add_value_to_release_types.php
Labels: size/S
