Repository faveosuite/faveo-invoicing-community, pull requests merged in 2024-07, with the labels that each got.

#3005 Apply fixes from StyleCI
  app/Http/Controllers/Subscription/SubscriptionController.php
Labels: size/M

#3006 Apply fixes from StyleCI
  app/Http/Controllers/Subscription/SubscriptionController.php
Labels: size/M

#3007 Apply fixes from StyleCI
  app/Http/Middleware/FixDebugbarMiddleware.php
Labels: size/XS

#3009 Apply fixes from StyleCI
  app/Http/helpers.php
Labels: size/XS

#3011 Apply fixes from StyleCI
  config/queue.php
Labels: size/XS

#3012 Apply fixes from StyleCI
  app/Http/Controllers/Order/OrderController.php
Labels: size/M

#3008 Debugger issue fixed
  app/Http/Kernel.php
  app/Http/Middleware/FixDebugbarMiddleware.php
Labels: Code Approved, QA: Functionality Approved, QA: Round 1 Testing Approved, size/S, PD: Demo Approved, QA: Round 2 Testing Approved

#3014 Apply fixes from StyleCI
  app/Http/Controllers/RazorpayController.php
Labels: size/XS

#3015 Apply fixes from StyleCI
  app/Http/Controllers/Common/MailChimpController.php
  app/Http/Controllers/HomeController.php
Labels: size/S

#3018 Apply fixes from StyleCI
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/License/LicenseController.php
  app/Http/Controllers/Order/BaseOrderController.php
Labels: size/S

#3019 Apply fixes from StyleCI
  app/Http/Controllers/Common/MailChimpController.php
Labels: size/XS

#3021 Apply fixes from StyleCI
  app/Http/Controllers/HomeController.php
Labels: size/XS

#3023 Apply fixes from StyleCI
  app/Http/Controllers/Order/OrderController.php
Labels: size/M

#3024 Apply fixes from StyleCI
  app/Http/Controllers/HomeController.php
Labels: size/XS

#3025 Apply fixes from StyleCI
  config/horizon.php
Labels: size/XS

#3032 Apply fixes from StyleCI
  app/Http/Controllers/Common/MailChimpController.php
Labels: size/XS

#3034 Apply fixes from StyleCI
  app/Http/Controllers/BaseHomeController.php
  app/Http/Controllers/License/LicenseController.php
Labels: size/S

#3035 Apply fixes from StyleCI
  app/Http/Controllers/BaseHomeController.php
  app/Http/Controllers/License/LicenseController.php
  app/Http/Controllers/Order/OrderController.php
Labels: size/XS

#3038 Apply fixes from StyleCI
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/License/LicenseController.php
  app/Http/Controllers/Order/BaseOrderController.php
  app/Model/Configure/ConfigGroup.php
  app/Model/Configure/ConfigOption.php
  app/Model/Configure/ConfigOptionValue.php
  app/Model/Configure/ProductPluginGroup.php
  app/Model/Product/Product.php
  database/migrations/2024_07_24_050427_create_config_group_table.php
  database/migrations/2024_07_24_050435_create_config_option_table.php
  database/migrations/2024_07_24_050450_create_config_option_values_table.php
  database/migrations/2024_07_24_050527_create_product_plugin_group_table.php
Labels: size/M

#3039 Apply fixes from StyleCI
  app/Http/Controllers/HomeController.php
Labels: size/XS

#3041 Apply fixes from StyleCI
  app/Model/Configure/PluginCompatibleWithProducts.php
  app/Model/Product/Product.php
Labels: size/XS
