Repository faveosuite/faveo-invoicing-community, pull requests merged in 2024-12, with the labels that each got.

#3160 Apply fixes from StyleCI
  app/Http/Controllers/Product/BaseProductController.php
Labels: size/XS

#3166 Apply fixes from StyleCI
  app/Http/helpers.php
Labels: size/XS

#3167 Apply fixes from StyleCI
  bootstrap/cache/packages.php
  bootstrap/cache/services.php
Labels: size/XXL

#3169 Apply fixes from StyleCI
  database/migrations/2017_06_10_062632_add_foreign_keys_to_configurable_options_table.php
  database/migrations/2017_06_10_062632_add_foreign_keys_to_group_features_table.php
  database/migrations/2017_06_10_062632_add_foreign_keys_to_invoice_items_table.php
  database/migrations/2017_06_10_062632_add_foreign_keys_to_order_invoice_relations_table.php
  database/migrations/2017_06_10_062632_add_foreign_keys_to_orders_table.php
  database/migrations/2017_06_10_062632_add_foreign_keys_to_prices_table.php
  database/migrations/2017_06_10_062632_add_foreign_keys_to_tax_product_relations_table.php
Labels: size/S

#3170 Apply fixes from StyleCI
  app/Http/Controllers/Product/BaseProductController.php
Labels: size/XS

#3171 Apply fixes from StyleCI
  app/Http/Controllers/License/LicenseController.php
  app/Http/Controllers/Product/BaseProductController.php
Labels: size/XS

#3172 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
Labels: size/XS

#3173 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
Labels: size/XS

#3174 Apply fixes from StyleCI
  app/Model/Product/Product.php
Labels: size/XS

#3175 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
  lang/en/message.php
Labels: size/S

#3176 Beta Release Issue
  app/Http/Controllers/HomeController.php
Labels: QA: Functionality Approved, Requires Code Review, size/XS

#3177 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Auth/BaseAuthController.php
  lang/en/message.php
Labels: size/XS

#3180 Apply fixes from StyleCI
  app/Http/Controllers/Auth/BaseAuthController.php
Labels: size/XS

#3186 Apply fixes from StyleCI
  app/Http/Controllers/License/LicenseController.php
Labels: size/XS

#3187 Apply fixes from StyleCI
  app/Http/Controllers/License/LicenseController.php
Labels: size/XS

#3190 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
Labels: size/XS

#3192 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
Labels: size/XS
