Repository faveosuite/faveo-invoicing-community, pull requests merged in 2024-01, with the labels that each got.

#2841 Remember me Fixed
  resources/views/themes/default1/front/auth/login-register.blade.php
Labels: QA: Functionality Approved, size/XS, PD: Demo Approved

#2849 Apply fixes from StyleCI
  app/Http/Controllers/Front/ClientController.php
Labels: size/XS

#2851 Apply fixes from StyleCI
  app/Http/Controllers/License/LocalizedLicenseController.php
Labels: size/XS

#2853 Apply fixes from StyleCI
  app/Http/Controllers/Order/RenewController.php
Labels: size/XS

#2854 Apply fixes from StyleCI
  bootstrap/cache/packages.php
  bootstrap/cache/services.php
Labels: size/XXL

#2855 Apply fixes from StyleCI
  app/Http/Controllers/Front/ClientController.php
Labels: size/S

#2856 Apply fixes from StyleCI
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/User/AdminOrderInvoiceController.php
Labels: size/S

#2865 Apply fixes from StyleCI
  app/Http/Controllers/Front/CartController.php
  app/Http/Controllers/Order/RenewController.php
Labels: size/M

#2866 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Front/PageController.php
Labels: size/S

#2869 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Google2FAController.php
Labels: size/S

#2870 Apply fixes from StyleCI
  app/Http/Controllers/Order/BaseOrderController.php
Labels: size/XS

#2871 Apply fixes from StyleCI
  app/Http/Controllers/Front/PageController.php
Labels: size/S

#2879 Update README.md
  README.md
Labels: size/M

#2882 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Auth/BaseAuthController.php
Labels: size/S

#2884 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Auth/BaseAuthController.php
Labels: size/XS

#2885 Apply fixes from StyleCI
  app/Http/Controllers/Front/PageController.php
Labels: size/L

#2886 Apply fixes from StyleCI
  app/Http/Controllers/Front/PageController.php
  app/Http/Requests/Front/ContactRequest.php
Labels: size/S
