Repository faveosuite/faveo-invoicing-community, pull requests merged in 2025-01, with the labels that each got.

#3194 Apply fixes from StyleCI
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/helpers.php
Labels: size/XS

#3201 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
Labels: size/XS

#3202 Apply fixes from StyleCI
  app/Http/helpers.php
Labels: size/S

#3204 Apply fixes from StyleCI
  app/Helper/AttachmentHelper.php
  app/Http/Controllers/Common/FileManagerController.php
  routes/web.php
Labels: size/XS

#3205 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
Labels: size/XS

#3206 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/helpers.php
Labels: size/M

#3210 Apply fixes from StyleCI
  app/Http/Controllers/BillingInstaller/InstallerController.php
Labels: size/XS

#3214 Update readme 4 0 2 3
  README.md
Labels: size/M

#3215 Bug in api call
  app/Http/Controllers/License/LicenseController.php
Labels: size/XS, PD: Demo Approved

#3220 Apply fixes from StyleCI
  app/Plugins/Stripe/Controllers/SettingsController.php
Labels: size/XS

#3223 Apply fixes from StyleCI
  app/Http/Controllers/Auth/RegisterController.php
  lang/en/message.php
Labels: size/XS

#3224 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
  app/Model/Common/Setting.php
  database/migrations/2025_01_23_055046_add_mobile_iso_to_users_table.php
  database/migrations/2025_01_23_082653_add_phone_iso_to_settings_table.php
Labels: size/XS

#3228 Apply fixes from StyleCI
  app/Model/Product/Product.php
Labels: size/XS

#3230 Apply fixes from StyleCI
  app/Http/Controllers/Auth/BaseAuthController.php
  app/Http/Controllers/User/ClientController.php
Labels: size/XS

#3231 Apply fixes from StyleCI
  app/Http/Controllers/HomeController.php
Labels: size/XS
