Repository faveosuite/faveo-invoicing-community, pull requests merged in 2025-06, with the labels that each got.

#3528 Apply fixes from StyleCI
  app/Console/Commands/SetupTestEnv.php
  tests/Browser/Auth/LoginTest.php
Labels: size/S

#3533 Apply fixes from StyleCI
  app/Rules/CaptchaValidation.php
Labels: size/S

#3541 Apply fixes from StyleCI
  app/Auto_renewal.php
  app/ExportDetail.php
  app/Http/Controllers/Common/BaseSettingsController.php
  app/Http/Controllers/Common/SettingsController.php
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/Front/PageController.php
  app/Http/Controllers/License/LicenseController.php
  app/Http/Controllers/Payment/TaxController.php
  app/Http/Controllers/Product/BaseProductController.php
  app/Http/Controllers/Product/PlanController.php
  app/Http/Requests/User/ProfileRequest.php
  app/Model/Payment/TaxClass.php
  app/Model/Payment/TaxProductRelation.php
  app/User.php
  lang/en/message.php
  tests/Unit/Admin/User/ProfileControllerTest.php
  tests/Unit/Admin/User/SoftDeleteControllerTest.php
  tests/Unit/Client/Cart/BaseCartControllerTest.php
  tests/Unit/Client/Product/DownloadApiTest.php
Labels: size/L

#3551 Apply fixes from StyleCI
  app/Policies/Csp/CspPolicy.php
Labels: size/XS

#3434 Autorenewal Fixes
  app/Http/Controllers/FreeTrailController.php
  app/Http/Controllers/Front/CartController.php
  app/Http/Controllers/Jobs/QueueController.php
  app/Http/Controllers/Order/BaseRenewController.php
  app/Http/Controllers/Order/InvoiceController.php
  app/Http/Controllers/Order/RenewController.php
  app/Http/Controllers/Subscription/SubscriptionController.php
  app/Model/Order/InvoiceItem.php
  app/Plugins/Stripe/Controllers/ProcessController.php
  app/Plugins/Stripe/views/middle-page.blade.php
  database/migrations/2025_05_10_045732_add_product_id_to_invoice_items_table.php
  database/seeders/v4_0_2_4_RC_1/DatabaseSeeder.php
  resources/views/themes/default1/common/cron/cron-new.blade.php
  resources/views/themes/default1/common/cron/cron.blade.php
  resources/views/themes/default1/front/cart.blade.php
  resources/views/themes/default1/layouts/front/master.blade.php
  resources/views/themes/default1/product/product/edit.blade.php
  resources/views/themes/default1/renew/popup.blade.php
Labels: Code Approved :heart_eyes_cat:, QA: Functionality Approved, QA: Round 1 Testing Approved, size/XL, PD: Demo Approved :thumbsup:, QA: Round 2 Testing Approved

#3596 Apply fixes from StyleCI
  app/Console/Commands/SetupTestEnv.php
Labels: size/XS

#3623 Apply fixes from StyleCI
  tests/Unit/LoginTest.php
Labels: size/XS

#3637 Apply fixes from StyleCI
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
  database/migrations/2025_04_25_082917_create_stripe_table.php
  database/migrations/2025_04_25_084130_create_razorpay_table.php
  lang/en/message.php
  routes/web.php
  tests/Unit/Common/SettingsControllerTest.php
Labels: size/M

#3651 Apply fixes from StyleCI
  app/Traits/Upload/ChunkUpload.php
  lang/en/message.php
Labels: size/XS
