Repository faveosuite/faveo-invoicing-community, pull requests merged in 2025-05, with the labels that each got.

#3439 Apply fixes from StyleCI
  app/Http/Controllers/Common/PipedriveController.php
  app/Traits/ApiKeySettings.php
Labels: size/XS

#3441 Apply fixes from StyleCI
  app/Http/Controllers/Common/MSG91Controller.php
Labels: size/XS

#3446 Apply fixes from StyleCI
  app/Http/Controllers/Front/BaseCartController.php
  app/Http/Controllers/Front/CartController.php
  app/Http/Controllers/Front/CheckoutController.php
  app/Http/Controllers/Order/InvoiceController.php
  tests/Unit/Client/Cart/BaseCartControllerTest.php
Labels: size/M

#3391 Msg reports
  app/ApiKey.php
  app/Console/Commands/CleanupMsg91Reports.php
  app/Console/Kernel.php
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Auth/BaseAuthController.php
  app/Http/Controllers/Common/BaseSettingsController.php
  app/Http/Controllers/Common/CronController.php
  app/Http/Controllers/Common/MSG91Controller.php
  app/Http/Controllers/Common/SettingsController.php
  app/Model/Common/Msg91Status.php
  app/Model/Common/MsgDeliveryReports.php
  app/Model/Common/StatusSetting.php
  app/Model/Mailjob/Condition.php
  app/Traits/ApiKeySettings.php
  database/migrations/2025_03_28_190011_create_msg_delivery_reports_table.php
  database/migrations/2025_04_10_064002_add_msg_third_party_id_to_api_keys_table.php
  database/migrations/2025_04_16_064801_create_msg91_statuses_table.php
  database/migrations/2025_04_16_105409_add_column_to_status_settings.php
  database/migrations/2025_04_17_091103_add_msg91_days_to_expiry_mail_days_table.php
  database/seeders/v4_0_2_4_RC_1/DatabaseSeeder.php
  lang/en/message.php
  resources/views/mini_views/intl_tel_input.blade.php
  resources/views/themes/default1/common/admin-settings.blade.php
  resources/views/themes/default1/common/apikey.blade.php
  resources/views/themes/default1/common/cron/cron-new.blade.php
  resources/views/themes/default1/common/cron/cron.blade.php
  resources/views/themes/default1/common/sms/msgReports.blade.php
  resources/views/themes/default1/front/auth/login-register.blade.php
  resources/views/themes/default1/third-party/index.blade.php
  routes/web.php
  tests/Unit/Common/MSG91ControllerTest.php
Labels: Code Approved :heart_eyes_cat:, QA: Functionality Approved, size/XXL, PD: Demo Approved :thumbsup:

#3461 Apply fixes from StyleCI
  app/Http/Controllers/Common/PipedriveController.php
Labels: size/XS

#3463 Apply fixes from StyleCI
  app/Http/Controllers/Subscription/SubscriptionController.php
Labels: size/S

#3466 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/FreeTrailController.php
  app/Http/Controllers/Front/BaseCartController.php
  app/Http/Controllers/Front/CheckoutController.php
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/Front/WidgetController.php
  app/Http/Controllers/Order/InvoiceController.php
  app/Http/Controllers/Order/RenewController.php
  app/Http/Controllers/Tenancy/CloudExtraActivities.php
  app/Http/Requests/User/ProfileRequest.php
  app/Plugins/Razorpay/Controllers/SettingsController.php
  app/Plugins/Stripe/Controllers/SettingsController.php
  app/Traits/CoupCodeAndInvoiceSearch.php
  app/Traits/PaymentsAndInvoices.php
  database/factories/Model/Payment/PlanPriceFactory.php
  database/migrations/2025_04_25_082917_create_stripe_table.php
  database/migrations/2025_04_25_084130_create_razorpay_table.php
  lang/en/message.php
  routes/web.php
  tests/Unit/Client/Account/ProfileTest.php
  tests/Unit/Client/Cart/BaseCartControllerTest.php
  tests/Unit/Client/ClientFooterGeneralTest.php
  tests/Unit/Client/CloudActivitiesTest.php
  tests/Unit/Client/DashboardTest.php
  tests/Unit/Client/Invoice/ClientInvoiceController.php
  tests/Unit/Client/Order/ClientOrderControllerTest.php
  tests/Unit/Client/RegistrationTest.php
  tests/Unit/Client/StoreTest.php
  tests/Unit/LoginTest.php
Labels: size/XXL

#3469 Apply fixes from StyleCI
  app/Http/Controllers/Subscription/SubscriptionController.php
Labels: size/XS

#3477 Apply fixes from StyleCI
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/BaseHomeController.php
  app/Http/Controllers/Common/BaseMailChimpController.php
  app/Http/Controllers/Common/BaseSettingsController.php
  app/Http/Controllers/Common/PaymentSettingsController.php
  app/Http/Controllers/Common/SettingsController.php
  app/Http/Controllers/Front/BaseClientController.php
  app/Http/Controllers/Front/ClientController.php
  app/Http/Controllers/Github/GithubController.php
  app/Http/Controllers/License/LicenseController.php
  app/Http/Controllers/Order/OrderController.php
  app/Http/Controllers/Product/ExtendedBaseProductController.php
  app/Model/Github/Github.php
  app/Traits/ApiKeySettings.php
  config/app.php
  database/migrations/2025_04_17_043938_change_varchar_longtext_github_password.php
  lang/en/message.php
  routes/web.php
  tests/Unit/MailchimpControllerTest.php
Labels: size/L

#3489 Apply fixes from StyleCI
  bootstrap/cache/packages.php
  bootstrap/cache/services.php
Labels: size/XXL

#3490 Apply fixes from StyleCI
  tests/Unit/Common/PipedriveControllerTest.php
Labels: size/XS

#3495 Apply fixes from StyleCI
  app/Http/Controllers/Front/CartController.php
  app/Http/Controllers/Order/BaseRenewController.php
  app/Http/Controllers/Order/RenewController.php
Labels: size/XS

#3509 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Common/SettingsController.php
Labels: size/S
